name: Upload das imagens para o EFS

on:
  push:
    branchs:
      - "develop"
    paths:
      - '**/*.png'

jobs:
  upload_to_efs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Configurando as instancias
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo mkdir efs
          sudo mount -t efs -o tls fs-0d5a3daa8e7d13dcf.efs.us-east-1.amazonaws.com efs/

      - name: Upload das imagens para o EFS
        run: |
          aws efs create-mount-target --file-system-id fs-0d5a3daa8e7d13dcf.efs.us-east-1.amazonaws.com --subnet-id subnet-029ee61487163fa02 --security-groups sg-12345678
          aws efs describe-mount-targets --file-system-id fs-0d5a3daa8e7d13dcf.efs.us-east-1.amazonaws.com
          
          # Copiar apenas arquivos PNG para o EFS
          find . -name '*.png' -exec aws efs copy --source {} --destination fs-12345678:/path/to/efs \;

      - name: SNYK AUTH
        run : |
          snyk -d auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - name: Configure AWS CLI
        if: always() 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test aws cli
        if: always()
        run: aws sts get-caller-identity

      - name: Terraform Apply
        if: always()
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-5)
          terraform init
          terraform apply -var="github_sha=$COMMIT_SHA" --auto-approve
        env:
          GITHUB_SHA: ${{ github.sha }}